---
title: "R Functions"
author: "Fan"
date: "13 October 2017"
output: html_document
---

```{r}
my_sum <- function (add1, add2){
  sum <- add1 + add2
  return(sum)
}

result = my_sum(10,100)
result
```
```{r}
fahr_to_kelvin <- function(f) {
  if (!is.numeric(f)){
    stop("Input has to be number")
  }
  kelvin <- ((f - 32) * (5 / 9)) + 273.15
  return(kelvin)
}
today = fahr_to_kelvin("32")
today = fahr_to_kelvin(32)
today
```

```{r}
kelvin_to_fahr <- function(temp1){
  celsius <- (k - 273.15) / (5 / 9) + 32
  return(celsius)
}
tomorrow = kelvin_to_celsius("abc")
tomorrow = kelvin_to_celsius(273.15)
tomorrow
```
```{r}
kelvin_to_celsius <- function(temp) {
  celsius <- temp - 273.15
  return(celsius)
}
test = kelvin_to_celsius(273.15)
test
```
```{r}

celsius_to_fahr <- function (something){
  fahr <- ((something * 9) / 5) + 32
  return(fahr)
}
allday = celsius_to_fahr(0)
allday
```


```{r}
fahr_to_celsius <- function(f){
  celsius = ((f - 32) * (5 / 9)) 
  return(celsius)
}
yesterday = fahr_to_celsius (32)
yesterday

```

```{r}
f_k_c <- function(f){
  f_k = fahr_to_kelvin(f)
  k_c = kelvin_to_celsius(f_k)
  return(k_c)
}
result = f_k_c(30)
result
```

```{r}
fahr_to_celsius <- function(temp) {
  stopifnot(!is.numeric(temp))
  temp_k <- fahr_to_kelvin(temp)
  result <- kelvin_to_celsius(temp_k)
  return(result)
}

tt = fahr_to_celsius(30)
```
```{r}
gapminder_file <- "https://raw.githubusercontent.com/COMBINE-Australia/RNAseq-R/gh-pages/data/gapminder-FiveYearData.csv"
download.file(gapminder_file, destfile="gapminder-FiveYearData.csv")
gapminder <- read.csv("gapminder-FiveYearData.csv")
```



```{r}
# Takes a dataset and multiplies the population column
# with the GDP per capita column.
calcGDP <- function(dat) {
  gdp <- dat$pop * dat$gdpPercap
  return(gdp)
}

calcGDP(head(gapminder))
```

```{r}
calcGDP <- function(dat, year=NULL, country=NULL) {
  if(!is.null(year)) {
    dat <- dat[dat$year %in% year, ]
  }
  if (!is.null(country)) {
    dat <- dat[dat$country %in% country,]
  }
  gdp <- dat$pop * dat$gdpPercap
  
  new <- cbind(dat, gdp=gdp)
  return(new)
}
calcGDP(head(gapminder))
calcGDP(head(gapminder), country="Afghanistan")
calcGDP(gapminder, country="China")
calcGDP(gapminder, country="China", year = 2000)
calcGDP(gapminder, country=c("China","India"), year = c(1990:2000))
        
```

